version: "3.8"

services:

  nginx:
    image: nginx:alpine
    volumes:
      - honeypot-logs:/var/log/nginx/shared
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./banned.html:/usr/share/nginx/html/banned.html:ro
      - htpasswd:/etc/nginx/htpasswd
    restart: unless-stopped
    depends_on:
      - python-analyzer
      - redis
    networks:
      - dokploy-network

  python-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - honeypot-logs:/var/log/nginx/shared
      - analyzer-db:/app/db
    restart: unless-stopped
    environment:
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - dokploy-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - dokploy-network

  htpasswd-init:
    image: httpd:alpine
    volumes:
      - htpasswd:/output
    command: >
      sh -c "htpasswd -bc /output/.htpasswd ${DASHBOARD_USER:-jibril} ${DASHBOARD_PASS:-changeme} &&
             echo '.htpasswd berhasil dibuat'"
    restart: "no"

volumes:
  honeypot-logs:
  analyzer-db:
  redis-data:
  htpasswd:

networks:
  dokploy-network:
    external: true
